baseURL = 'https://jasonbirchall.github.io'
languageCode = 'en-uk'
title = 'Jason Birchall'
theme = 'risotto'
[params]

[params.theme]
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
#title = "danielunderwood.dev"
#description = "My personal website"

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/jasonbirchall"


[markup]
  [markup.highlight]
    codeFences = true
    noClasses = true
    style = "monokai"
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This is needed for <i> tags in markdown unless I can
      # figure out how to use shortcodes there
      unsafe = true

[menu]
  [[menu.main]]
    name = "Get Faster"
    url = "/get-faster/"
    weight = 1
  [[menu.main]]
    name = "Test Yourself"
    url = "/test-yourself/"
    weight = 2
  [[menu.main]]
    name = "Fill in the Gap"
    url = "/fill-in-the-gap/"
    weight = 3
  [[menu.main]]
    name = "Observe"
    url = "/observe/"
    weight = 4
  [[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 5
  [[menu.main]]
    name = "Fail"
    url = "/fail/"
    weight = 6
