# Generated by Django 5.2.15 on 2026-06-11 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_fts'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='link_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_source',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='quote_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='updated',
            field=models.DateField(blank=True, null=True),
        ),
    ]
