# Generated by Django 5.2.15 on 2026-07-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='WakaSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.TextField()),
                ('fetched_at', models.DateTimeField()),
            ],
        ),
    ]
