#ENC[AES256_GCM,data:IBxOlP+P71Ez3NZXu9KHMDFLZypihF4TynAeFEyUdc7If2DhcTXNtG0rYd/2Le7HoeaBKaWD6CgDIDiMWveSciIoYRyriNd6bME=,iv:uQvxZ6ttE8L04GMH4eXG2ykBSfy3Zh25DxqlJFtqsiY=,tag:f4ksDR03wD48V43q51A3bg==,type:comment]
#
#ENC[AES256_GCM,data:fCRgMJqMW9QWvUHieosfyI0TEJPAKwk=,iv:AgUON95nxc0HQEwbrGB4Yjs6yjen90YMzj5w3qOGvm0=,tag:PTuGV/MnI3vVEMyMuVIM3w==,type:comment]
#ENC[AES256_GCM,data:yUEH11M/O0L4pnfr29DBq83ji50sYc434+vqFHJQZYqQAGtMLh+7/tNMYvvZziVY3vf+i/GNzHjASGf8ez1qLV/pun4oD5LmQsoumjjNvQ==,iv:Tsk6Luf7E/FEedHD0NjFz9Q4NXevEPTyc8IwwqRMTWY=,tag:ERZrJ9u3JNtMKZ95s839Jw==,type:comment]
#ENC[AES256_GCM,data:demEITvPoh5bZdN9sUFVNZFC4djYMrlGrpc85b3WPGqp8vCXgnPYGz+cySB8kFxC3wjR0WKWwiFbntbMWB/PApGGjqxvZbkC,iv:Csxha5YanmW2qdZPH1ym5THm6jTczXCRG3Hi+Ml59Nc=,tag:FKgsOOjfZ4fvukZAB9bcdw==,type:comment]
#ENC[AES256_GCM,data:PJoh8bcs4uZuc+CHz3jWqnaNCJaS3MLWfE6fHjCt6Ext+U60m0+AxVS7EFWJn44owhX0X3lihAqXuntsEA==,iv:g3YK/XIY6u1q7rlzt2PG2sOicCAqW4FvnYqB24MtWyo=,tag:ip8T5hsRMcMxiygxf/dCyA==,type:comment]
#ENC[AES256_GCM,data:MnbYQZpZ4X4YyXoc6UXn9fwKYkt9drMdxd7JAlJFkWGI98X1IGPTDn3auD0jFV9m7eZb0paMOA6s13M=,iv:eYpuZIe+Tb+we5BFZNDm8a6o/F10Dt+45nbrWMorQYg=,tag:IvBVBNC+51a+QgELny6NXg==,type:comment]
#ENC[AES256_GCM,data:+GBZJM47huYpCEczTePD5ujRQYU=,iv:LEr4dJM9LoP90Mc4NEU1oCa7O7Qy7A/J1YZtuP66uG8=,tag:eYL17a/pAttBqPXON1qiWg==,type:comment]
#
#ENC[AES256_GCM,data:sf1H1tSt2IuYvALDWQ3vXgD4PXKW3xwG35Otpbqw3T2KLJ8oh9iCL/bQMdEemJH9HcsjwQ1Glyq/xPiRpjzqx/omf1jaxW58U7A=,iv:gWEXjt09RlCmChZdbGWxks4YycPUwsykAn0qj6qkLaI=,tag:aRSfR/BFoX+Jg7sOyWgfOQ==,type:comment]
#ENC[AES256_GCM,data:rqRtBChcrdsS2HreEyv3oTo59OggR57yAsOaoJNJ6umhhZcHce7/aT0fk1k6L7wpNVU=,iv:CyB6lcxz+t4IOqcCVpKFyE9J0PobdFxX6QRwmXMBu6A=,tag:1r1gY2I6gacEMj8jIk71aQ==,type:comment]
#ENC[AES256_GCM,data:Lxv9kALgnu2xN6kieeb6cu9MWmbrFG5NAtis3jr2z4QGjNcxjJY=,iv:S+W53RWkFrTtMbOEzfQIctG7H+PwI3DIM+J+lZt59Jw=,tag:31WYNyChYlF63bUMTCMRzQ==,type:comment]
TF_VAR_hcloud_token: ENC[AES256_GCM,data:7EOx+AGS6EkUeg==,iv:nYmRmwF+E60TuOKIik13fxwuq1HXwaT2p91juXpSWME=,tag:kxRSziof98PbstPoxeQMaQ==,type:str]
TF_VAR_gandi_pat: ENC[AES256_GCM,data:GFt8xyr0JCnOSA==,iv:BpGhHvG+SisnTeiGXqgDtfAUHxwX6er5bRM7sc86/Jo=,tag:kymieby3NOpxyffRu7vJkA==,type:str]
TF_VAR_object_storage_access_key: ENC[AES256_GCM,data:JPGhg9VT5kS71Q==,iv:OJNrbWXx1Iu1aodb7xsQubGYua4P13mG86CGp4ieuP4=,tag:vUFBElNxoHlYydY/A6xgRA==,type:str]
TF_VAR_object_storage_secret_key: ENC[AES256_GCM,data:mXscyHqOXAih/A==,iv:txqI0z9uuFLXAMIc7XKSyPQzN8ank5zlt10DIwoFB2I=,tag:8Ykw1tkBrY17Q4Ac9rVuLw==,type:str]
TF_VAR_tailscale_auth_key: ENC[AES256_GCM,data:WkOXlbdBAXPWUg==,iv:LFFXAM1l8SKWKy1+X/j5aiy1DPGqPLMBeFz2xsm8oQ4=,tag:kNdMr2vaQsG2c9xsTlazdQ==,type:str]
#ENC[AES256_GCM,data:g3tuiYQSzmg4GQftNyS6DnKGd6QxdYTEnDESXrmC0wIKQg55q7J8opAYbiI=,iv:E84TvSUQw3BfLczVdKRObJ8f1oJE+e7vvmxR0jydTtE=,tag:4Fh5ocRhE5lZxUNyTU3lEA==,type:comment]
django_secret_key: ENC[AES256_GCM,data:D8dbQio+49izNg==,iv:7CM15gWjMP63t+1DqB6tgjOG0by11niEHUgj7QgSPvQ=,tag:EFGd4UkPcLK1dP6iMrtfVA==,type:str]
proton_smtp_token: ENC[AES256_GCM,data:6pScUGWe9w1K1A==,iv:jKEBxoUGD6YBzK0Tk8m56IJ3vAAwUgZiY6XV4mA2b2I=,tag:Kjnqslt8snf7ysN7lHZ21w==,type:str]
healthchecks_ping_url: ENC[AES256_GCM,data:dUU8ookFajZt4w==,iv:CTBmLu30PUlQqvlDRuqrN2fjw2reYLr1w2f1sN9z+bQ=,tag:+8L0rlQSowkcflfE8Knd7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUWtoNmQrMlNYemxMMERp
            bUNPYmpOWG9Hd24vbzVhOGswanZ1Y0U1ZFNNCkVCV0FkaldtR1ZZUVh6cXFZQTBZ
            emE4YnlJam9QNmtRQjdvcDJmRk9pWXMKLS0tIFp2cDdLNWxkeFlTSVgvblF0Y2o1
            cGRPWjBhVEVNL3BZMFl5OG1hc0wzUlEKW2wLOFyagj13O0UBjWhr1VUrlGKadB8W
            DtZzul2Hhw7Ir8zGXRYpa2rLraeixV/qrFv5EmnhJqm6VUlow7gXWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzxv84tehrhklt2avxfwr4fg05p6z9l7wfjly4cfeg8tj9ffrffqqwz0a9
    lastmodified: "2026-06-15T16:22:19Z"
    mac: ENC[AES256_GCM,data:1fqFaZSNvo/Fo6JmNoXRW4QoXbhseNe3aeCMThTSPxDAccV7dnSJyEKevCW05a2XhDC82Ykk1GtslT7uqT2wZkkFbL+eoLPl2aBF+z/gncx/F5CLy1QWstX+mPabQaPdGyGSuXyAuREQ7K2VRaEzkO68fOmlPd0/ysZh9ea1SsE=,iv:jGnTf+ffixh5qFTnefjFq0RfZonGa8ZQ6/ZWlSpD1+A=,tag:SkzoZ28SAxZjz9EIDc/oEA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
