#ENC[AES256_GCM,data:TjxoLw0VCvjp2GAT+3mY64nlQs/IvjEzR4qhUplwa0REGS9H6yW79ZwACA8chE4r1W64ADXRwfXS7y+h5VtGtX91N1vV+0tKcmE=,iv:Sjr6Wjw3BDpMWy+tjvk99t9Fz5Zvso8GgONMOS+/FgQ=,tag:19wIRlmLjgmB5wJdRnm33g==,type:comment]
#
#ENC[AES256_GCM,data:Je+bsmYfX//1ENQxiKuJKVq+bMnxkDw=,iv:p5DCaY1k5UxCDcQM1ZVFxdGZhptxYSJ12oKP5tP4yO0=,tag:/RD0/ZOQ7sIuYDpFPceRoA==,type:comment]
#ENC[AES256_GCM,data:eubCIrR/XiMalUUidYhIFNz1WaFmYa1rQsf+M613ay/1IHS2ywslyNPvG42lM13xFKtfr6Jn/T1uaz+twoo9pUfw/FgrImZT4/6TpO+asw==,iv:eCRvwnfZfPlt6+A3UAP9tGJJrYWZ0+omLpLLNFemzX0=,tag:0S8lPgk15n+dyU0Koqv6Lg==,type:comment]
#ENC[AES256_GCM,data:jxHC/N1ruP2wuddSNNwQwvTtFAg4fKc6GLS8s2vB8zx1HmZx0eOaeoS8o5+GfibkeJkoDPqkfB8o7Vs7WMrA0F9vituunQkc,iv:KfIi2zjVeNR2KTFgQEPtyweJfyT3AA7JzOfkYKUBsho=,tag:+/QDSH9WJk+BUVT4/iCapw==,type:comment]
#ENC[AES256_GCM,data:URYvwfFFqfhsw0D/cRp6gfEY5okG4bTGi1Hxd8VZpCPpDrRv9vGTFXqMbS/QQE5a0wmsa/65mDPmstpvfw==,iv:y2XuxvJMa4iTQ25Kis1xv056qBLGgopLkExSprPzOC0=,tag:zaF/u1Gg8CaqipFH4PmtGw==,type:comment]
#ENC[AES256_GCM,data:8z0JN2iA2qd1ij7pKKCr4kK083UHj06xrPSbiqvGyyTBS4ARzLJdDmJP59tE7uObGkTShnwqUmBMl6Y=,iv:UkY3aYKmtFwmIJ1LOA06FFc8wMMBjVz4KqOqst0XhvY=,tag:uITS4YBmAHp6RCJPRcS17A==,type:comment]
#ENC[AES256_GCM,data:PRwPVzX4cyknJbenZZ/vp0M1sy0=,iv:iZvR7zdAiCmi8e8t0iPRIA4w6bagFZpmmzYTBDMHTi0=,tag:Bz3zPLYiLCzlm4SWLJdHDw==,type:comment]
#
#ENC[AES256_GCM,data:7yKNW1KkDTWMDlSuwu3NKw5hn7TauoaJlnyuLZDXF06bU9t/yQ23zZ52DX6BEakCkQkq9yfEpwaWSmxYxhJNiuNnSA/cmNbhqyY=,iv:/iZrfRgTqbtvpDKPlfiCsBBo0xSw1XCrjUNcKknXRP4=,tag:W9jqBfkPO4mvynrQXgijgw==,type:comment]
#ENC[AES256_GCM,data:pEHFwnUynQWTNO8kWMwbqp0mj5Ici2HsCsnU65dhHx3qax9wjQjX3/xbOr4HLhRPOA4=,iv:rcsx5xHNyrR9Nx+lL2nPEeNbqTFuPMwlTssrFKObiNo=,tag:Oef3BclhWPrX7tPAwKoqSg==,type:comment]
#ENC[AES256_GCM,data:tY/sxMyxccH7gDCCRrob7W+a7DhR/Iiq8D7XcyYIcMAMHowI/O0=,iv:KAMSvrFhrPjoXVYDYtWS6TQB9FtG4SWhsDXTxSlHCs0=,tag:CC6WOK0Hej4T5TFYE69OCQ==,type:comment]
TF_VAR_hcloud_token: ENC[AES256_GCM,data:Oe/Xa4NbO2YpPw==,iv:r+pcZ3Bqo1DGF5XgQTs2+lrvzHOuVYi2oMcpg9zvEtU=,tag:dPBlo9eOLCzqqjZ/FDkEUA==,type:str]
TF_VAR_gandi_pat: ENC[AES256_GCM,data:qmrjzVazx0WatQ==,iv:jA3XsYPRxiCOA3EDMXp1mWG6LKyrNdbe8k5AoKSf2gU=,tag:npg2BXboWmJEkMfMuGdRig==,type:str]
TF_VAR_object_storage_access_key: ENC[AES256_GCM,data:Ils6CJsdbB60mA==,iv:cVvGdpYEjuJ1c/v0h8eDmWSOdqPCrGDdsG0EzOAG7fc=,tag:wab1TKNGjl5oUEqyiSVj/Q==,type:str]
TF_VAR_object_storage_secret_key: ENC[AES256_GCM,data:W37v2E3o2WfzjQ==,iv:bzu1ECZ0QnoPTBGxjga4gRKKCigBKGyUM+s7u/lEgpo=,tag:pQrmsv6jGJQdGJZ9zqHcZw==,type:str]
TF_VAR_tailscale_auth_key: ENC[AES256_GCM,data:M/QEAmMgrJlcjw==,iv:2TTOn06jwdMB6bUu7guvXZlryUKPV6P+NtcgpPnxHMw=,tag:BvAmay/LZxa9p5I6f3zXhg==,type:str]
#ENC[AES256_GCM,data:aq1BauLfc01idu2oX/oyRybWPMhDZXD90VoVIRg3QIRfem1+wy5GTvpzoqI=,iv:jObCzIa0knEIUppikmDTofKtHajCl8zFnoQZ+4o6bY0=,tag:JKc6KrSYn7Zi5B1pCPmWNg==,type:comment]
django_secret_key: ENC[AES256_GCM,data:DWw2Kuc3htXviA==,iv:gfffBicu1bNKoF7Rb19/CEJMIrUpq7dDc4bqvvZ40Ao=,tag:D1gE85zjyWuZ2K793oXJ0g==,type:str]
proton_smtp_token: ENC[AES256_GCM,data:7WVAkeS7GKI4VQ==,iv:kjShyU7E901h6gVmSwwoCaD1zBQACVoeCCrHi2fF61g=,tag:r01ERh+rYqt1vyJonF1kFg==,type:str]
healthchecks_ping_url: ENC[AES256_GCM,data:cxw4vmtnRkW7QQ==,iv:ZZzUqcvJ+YQPIDysG9jNXy2OuwgK1woKo70h6zFLbQU=,tag:dODudB3PCFFJsvEiSjQ2FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzazBPeXZxT3ljYXRNS0cx
            ZHlNbjdBemNqYmVUei85eDJuS0prZ2sxZUYwCkFXMW9pSkF2ZEpYQ3hWYk5zSGJs
            dk9abnZuMlBMMVFnRnZoOUpkVDZRRUEKLS0tIEJIcVBuRVBXUTBtdHl5TDRVUE5n
            dCs1Qk42aEptcTFTYzRKMlkxSVVEbjgKogZHxM2UoVHJRSKJm8i7+3uiPMoCzL8H
            pflByCGt1yuA6KV1cyhnYcSTeFW3xfWXRHaVMfibersdfw0Pv4p+fw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zzxv84tehrhklt2avxfwr4fg05p6z9l7wfjly4cfeg8tj9ffrffqqwz0a9
    lastmodified: "2026-06-15T16:29:00Z"
    mac: ENC[AES256_GCM,data:w5hsikkjGtM0KMctl4ATIXgC3t4td60sbtGDy90IvVrk8EHcJCFs1Kj17SaWhFzSzL6E7LPrMvkhNmCJAv0JzFSioXZimujfIu3e3/Om9n8bWDB8WAZdmEIzjmxQjik8suIlZqaX98BaVVeILkPniKer7ff1FFpRgtCa6EiCgUM=,iv:mO3446+T7cgrR+AizbDRmYxNczmIbhHD2VkZ2w5k2Ks=,tag:bTG/sNPN+xUwekEOz85Ffw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
